### ISSUE TITLE
Generate MachineVision ModelDesign format from NodeSet2 format

### ISSUE THREAD

**Issue by eoursel** [mpostol/UA-Nodeset#7]
Hi @mpostol  

When i generate the ModelDesign format for [Machine Vision specification](https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/MachineVision/Opc.Ua.MachineVision.NodeSet2.xml) i notice that many namespaces are created in the model design specification. The output file contains up to 180 namespaces such as at the end of the file

`<ObjectType xmlns:q180="http://opcfoundation.org/UA/MachineVision" SymbolicName="q180:VisionSystemType">`

Not sure this behavior is expected? Is there any reason to do that? 
[Opc.Ua.MachineVision.ModelDesign.xml.zip](https://github.com/mpostol/OPC-UA-OOI/files/5081156/Opc.Ua.MachineVision.ModelDesign.xml.zip)

**Comment by mpostol** [comment]
@eoursel This issue has been transferred here because the work is to be continued here.

**Comment by mpostol** [comment]
It contributes to #8.

**Comment by mpostol** [comment]
The import works and reports the following model errors:

``` txt
Trace: Information, Error Focus: NodeClass, Identifier: P3-0503020000 Description: Unexpected value of the InverseName. If ReferenceType 1:FromTransition is not symmetric and not abstract the InverseName shall be specified.
Trace: Information, Error Focus: NodeClass, Identifier: P3-0503020000 Description: Unexpected value of the InverseName. If ReferenceType 1:ToTransition is not symmetric and not abstract the InverseName shall be specified.
```

The model contains a bunch of redundant xmlsn redefinitions for the `http://opcfoundation.org/UA/MachineVision`.

**Comment by mpostol** [comment]
Reported issue `6820` on [mantis](https://mantis.opcfoundation.org/view.php?id=6820)

**Comment by mpostol** [comment]
@eoursel  I believe that the problem was fixed in pr #20. I will appreciate a review of the [ModelDesign](https://raw.githubusercontent.com/mpostol/UA-Nodeset/main/MachineVision/ModelDesign/Opc.Ua.MachineVision.Model.xml).

I have closed this issue as a result of the merge, but you must feel free to open it again and report any problems you find, or, alternatively, open a new issue. 

The model has been generated by the Address Space Prototyping (asp.exe) 6.3.0.34196. This tool uses the same packages as the Address Space Designer, co my plan looks as follows:

- continue further development of the asp ( I will test asp against all the models in the mpostol/UA-Nodeset.The result you can find in the ModelDesign folder) 
- release all NuGet packges
- release asp
- ASMD - update packages to get the same functionality
- release ASMD

Let me know how it works for you.

**Comment by eoursel** [comment]
thanks @mpostol, i will ask someone in my team to test that. i am quite busy working for a customer up to the summer not doing OPC UA but something related to data modeling..

Regards

**Comment by mpostol** [comment]
@eoursel , sure, I will do my best in any case questions or proposal you may have but I am also thinking about information modeling, not in the context of OPC UA but still resuing selected concepts derived from OPC UA. There is a discussion you may be interested mpostol/OPC-UA-OOI#587, Maybe you will be willing to add your 10 cents.

Good luck and let's stay in touch.

**Comment by eoursel** [comment]
hi @mpostol, happy to see a good progress.. i am back to OPC UA after a difficult Entreprise Architecture production project (though not completely finished). I see you have generated some ModelDesign outputs for public OPC Foundation models. What is the status? Are you able to test that the UAModelCompiler is able to digest these files and generate valid outputs?   Thanks

**Comment by mpostol** [comment]
Hi @eoursel, I am after a short vacation, so I will summarise the current status of the work as a new prerelease very soon. 

Anyway, all generated ModelDesign are ready to be compiled by OPF UAModelCompiler.

We must be concerned about how to compare and validate the result because the same model may be represented by many XML files compliant with the schema (OPCFoundation/UA-ModelCompiler#75). I call it semantic diff - it is on my road map, but no priority is assigned to it - just in the backlog. As far as I know, a working group is working on it also.

**Comment by mpostol** [comment]
HI @eoursel, I have just summarised the current status of the work as a new prerelease [2.0.0-Alpha](https://github.com/mpostol/UA-Nodeset/releases/tag/2.0.0-Alpha). 
Any question or proposal you may have please report as:

- create a new issue
- add comments  using the discussion dedicated panel #57.
